/**
 * Random training scenarios. Nothing here knows the "answer" up front: every
 * scenario is generated by dealing cards / simulating legal betting with the
 * engine, and the answer is then DERIVED by the rules engine
 * (evaluateHand / determineWinners / calculatePot).
 *
 * Difficulty levels (1..5) only change WHAT gets generated (player counts,
 * streets, which situations are accepted by rejection sampling); the answer
 * is always computed the same way.
 */
import { Card } from "./cards";
import { createDeck } from "./deck";
import { createRng, randomSeed, Rng, shuffle } from "./shuffle";
import { evaluateHand, HandCategory, HandValue, HAND_CATEGORIES } from "./handEvaluator";
import { compareHands, determineWinners } from "./handComparator";
import {
  Action, applyAction, HandHistory, HandState, isRoundComplete, legalActions, PlayerSetup, startHand, startStreet, Street, STREETS,
} from "./betting";
import { calculatePot, PotResult } from "./potCalculator";
import { Pot } from "./sidePotCalculator";
import { classifyHandReading, classifyPot, classifySidePot, classifyWinner, isBoardPlay, Mode, SkillId, SKILLS } from "./skills";
import { Level } from "./rating";

export type { Mode, SkillId };
export const MODES: readonly Mode[] = ["hand-reading", "winner", "pot", "side-pot"];

export interface GenerateOptions {
  level?: Level;
  seed?: number;
  /** Skills the trainee is weak at; the generator biases toward scenarios that exercise them. */
  weakSkills?: readonly SkillId[];
}

export interface SeatCards {
  seat: number;
  name: string;
  holeCards: Card[];
}

interface ScenarioBase {
  seed: number;
  level: Level;
  skills: SkillId[];
}

export interface HandReadingScenario extends ScenarioBase {
  mode: "hand-reading";
  holeCards: Card[];
  board: Card[];
  answer: { category: HandCategory; hand: HandValue };
}

export interface WinnerScenario extends ScenarioBase {
  mode: "winner";
  board: Card[];
  buttonSeat: number;
  players: SeatCards[];
  answer: {
    /** All winning seats. Length > 1 means a split pot. */
    winners: number[];
    split: boolean;
    hands: { seat: number; hand: HandValue }[];
  };
}

export interface PotScenario extends ScenarioBase {
  mode: "pot";
  history: HandHistory;
  /** Community cards dealt for the streets that were played (display only). */
  board: Card[];
  result: PotResult;
  answer: { pot: number };
}

export interface SidePotScenario extends ScenarioBase {
  mode: "side-pot";
  history: HandHistory;
  board: Card[];
  result: PotResult;
  answer: { pots: Pot[]; uncalled: { seat: number; amount: number } | null };
}

export type Scenario = HandReadingScenario | WinnerScenario | PotScenario | SidePotScenario;

// ---------------------------------------------------------------------------
// helpers

function dealer(rng: Rng) {
  const deck = shuffle(createDeck(), rng);
  let i = 0;
  return (n: number): Card[] => {
    if (i + n > deck.length) throw new Error("deck exhausted");
    const out = deck.slice(i, i + n);
    i += n;
    return out;
  };
}

function weightedPick<T>(rng: Rng, items: readonly { item: T; weight: number }[]): T {
  const total = items.reduce((s, x) => s + x.weight, 0);
  let r = rng.next() * total;
  for (const x of items) {
    r -= x.weight;
    if (r < 0) return x.item;
  }
  return items[items.length - 1].item;
}

function playerName(seat: number): string {
  return `Player ${seat}`;
}

function levelOf(o: GenerateOptions | undefined): Level {
  const l = o?.level ?? 1;
  return (Math.min(5, Math.max(1, Math.round(l))) as Level);
}

function hasWeak(skills: readonly SkillId[], weak: readonly SkillId[] | undefined): boolean {
  return !!weak && skills.some((s) => weak.includes(s));
}

/**
 * Weak skills that belong to this mode. The 50% "drill a weak skill" decision
 * uses its own rng stream so it never shifts the main deal sequence: a seed
 * reproduces the same scenario whether or not the profile has weak skills
 * (unless a relevant weak skill is actually being drilled).
 */
function weakFor(mode: Mode, seed: number, weak: readonly SkillId[] | undefined): SkillId[] {
  const relevant = (weak ?? []).filter((s) => SKILLS[s].mode === mode);
  if (relevant.length === 0) return [];
  return createRng((seed ^ 0x51ed27a1) >>> 0).chance(0.5) ? relevant : [];
}

// ---------------------------------------------------------------------------
// HAND READING

interface HRDeal { hole: Card[]; board: Card[]; hand: HandValue; skills: SkillId[] }

function dealHR(rng: Rng): HRDeal {
  const deal = dealer(rng);
  const hole = deal(2);
  const board = deal(5);
  const hand = evaluateHand([...hole, ...board]);
  return { hole, board, hand, skills: classifyHandReading(hole, board, hand) };
}

function distinctRankRun(cards: readonly Card[]): number {
  // longest run of consecutive distinct ranks (ace counts high and low)
  const set = new Set<number>(cards.map((c) => c.rank));
  if (set.has(14)) set.add(1);
  let best = 0;
  for (let start = 1; start <= 14; start++) {
    let len = 0;
    while (set.has(start + len)) len++;
    best = Math.max(best, len);
  }
  return best;
}

function suitedCount(cards: readonly Card[]): number {
  const m = new Map<string, number>();
  for (const c of cards) m.set(c.suit, (m.get(c.suit) ?? 0) + 1);
  return Math.max(...m.values());
}

type HRPredicate = (d: HRDeal) => boolean;

const cat = (...cs: HandCategory[]): HRPredicate => (d) => cs.includes(d.hand.category);
const notBoardPlay: HRPredicate = (d) => !isBoardPlay(d.hand, d.board);
const and = (...ps: HRPredicate[]): HRPredicate => (d) => ps.every((p) => p(d));

/** Per level: weighted list of acceptance predicates. One is picked, then deals are rejected until it matches. */
const HR_LEVELS: Record<Level, { item: HRPredicate; weight: number }[]> = {
  1: [
    { item: and(cat(HandCategory.OnePair), notBoardPlay, (d) => d.hole[0].rank === d.hole[1].rank || d.hole.some((h) => h.rank === d.hand.tiebreak[0])), weight: 30 },
    { item: and(cat(HandCategory.Straight), notBoardPlay, (d) => d.hand.tiebreak[0] !== 5), weight: 25 },
    { item: and(cat(HandCategory.Flush), notBoardPlay, (d) => suitedCount([...d.hole, ...d.board]) === 5), weight: 25 },
    { item: and(cat(HandCategory.HighCard), notBoardPlay), weight: 10 },
    { item: and(cat(HandCategory.FourOfAKind), notBoardPlay), weight: 10 },
  ],
  2: [
    { item: and(cat(HandCategory.TwoPair), notBoardPlay), weight: 35 },
    { item: and(cat(HandCategory.ThreeOfAKind), notBoardPlay), weight: 30 },
    { item: and(cat(HandCategory.FullHouse), notBoardPlay), weight: 35 },
  ],
  3: [
    { item: (d) => d.skills.includes("kicker-selection"), weight: 60 },
    { item: and(cat(HandCategory.ThreeOfAKind), notBoardPlay, (d) => d.hole.some((h) => d.hand.bestFive.some((b) => b.rank === h.rank && b.suit === h.suit) && h.rank !== d.hand.tiebreak[0])), weight: 20 },
    { item: and(cat(HandCategory.OnePair), (d) => d.hole.every((h) => h.rank !== d.hand.tiebreak[0]) && d.hole.some((h) => d.hand.bestFive.some((b) => b.rank === h.rank && b.suit === h.suit))), weight: 20 },
  ],
  4: [
    { item: and(cat(HandCategory.Straight), (d) => isBoardPlay(d.hand, d.board)), weight: 30 },
    { item: and(cat(HandCategory.Flush), (d) => isBoardPlay(d.hand, d.board)), weight: 20 },
    { item: and(cat(HandCategory.TwoPair, HandCategory.ThreeOfAKind), (d) => isBoardPlay(d.hand, d.board)), weight: 20 },
    { item: and(cat(HandCategory.FullHouse, HandCategory.FourOfAKind), (d) => isBoardPlay(d.hand, d.board)), weight: 15 },
    { item: and(cat(HandCategory.HighCard, HandCategory.OnePair), (d) => isBoardPlay(d.hand, d.board)), weight: 15 },
  ],
  5: [
    { item: (d) => d.skills.includes("counterfeit"), weight: 20 },
    { item: and(cat(HandCategory.Straight, HandCategory.StraightFlush), (d) => distinctRankRun([...d.hole, ...d.board]) >= 6), weight: 20 }, // a higher straight exists among the 7 cards
    { item: and(cat(HandCategory.Flush), (d) => suitedCount([...d.hole, ...d.board]) >= 6), weight: 15 },
    { item: and(cat(HandCategory.FullHouse), (d) => { const c = new Map<number, number>(); for (const x of [...d.hole, ...d.board]) c.set(x.rank, (c.get(x.rank) ?? 0) + 1); const v = [...c.values()]; return v.filter((n) => n >= 3).length >= 2 || v.filter((n) => n === 2).length >= 2; }), weight: 15 },
    { item: (d) => d.skills.includes("wheel-straight"), weight: 10 },
    { item: and(cat(HandCategory.TwoPair, HandCategory.FullHouse, HandCategory.FourOfAKind), (d) => { const c = new Map<number, number>(); for (const x of d.board) c.set(x.rank, (c.get(x.rank) ?? 0) + 1); return [...c.values()].filter((n) => n >= 2).length >= 2; }), weight: 10 }, // double paired board
    { item: cat(HandCategory.StraightFlush), weight: 5 },
    { item: and(cat(HandCategory.FourOfAKind), (d) => d.board.filter((b) => b.rank === d.hand.tiebreak[0]).length >= 3), weight: 5 },
  ],
};

export function generateHandReading(opts: GenerateOptions = {}): HandReadingScenario {
  const seed = opts.seed ?? randomSeed();
  const level = levelOf(opts);
  const rng = createRng(seed);
  const predicate = weightedPick(rng, HR_LEVELS[level]);
  const weak = weakFor("hand-reading", seed, opts.weakSkills);
  const wantWeak = weak.length > 0;
  // Rejection sampling keeps every deal an honest random 7 cards while making
  // the level's situations show up. Fallback: the last deal.
  const maxTries = 40000;
  let fallback: HRDeal | null = null;
  let chosen: HRDeal | null = null;
  for (let t = 0; t < maxTries; t++) {
    const d = dealHR(rng);
    fallback = d;
    if (wantWeak && t < 3000) {
      // Weak-skill drill: only accept deals that exercise a weak skill (then fall back to the level predicate).
      if (hasWeak(d.skills, weak)) { chosen = d; break; }
      continue;
    }
    if (predicate(d)) { chosen = d; break; }
  }
  const d = chosen ?? fallback!;
  return { mode: "hand-reading", seed, level, skills: d.skills, holeCards: d.hole, board: d.board, answer: { category: d.hand.category, hand: d.hand } };
}

// ---------------------------------------------------------------------------
// WINNER

interface WDeal {
  board: Card[];
  players: SeatCards[];
  result: ReturnType<typeof determineWinners<number>>;
  skills: SkillId[];
  fullSplit: boolean;
  partialSplit: boolean;
}

function dealWinner(rng: Rng, playerCount: number): WDeal {
  const deal = dealer(rng);
  const players: SeatCards[] = [];
  for (let s = 1; s <= playerCount; s++) players.push({ seat: s, name: playerName(s), holeCards: deal(2) });
  const board = deal(5);
  const result = determineWinners(players.map((p) => ({ id: p.seat, holeCards: p.holeCards })), board);
  const fullSplit = result.winners.length === players.length;
  const partialSplit = result.winners.length > 1 && !fullSplit;
  const skills = classifyWinner(result.hands.map((h) => ({ seat: h.id, hand: h.hand })), result.winners, board);
  return { board, players, result, skills, fullSplit, partialSplit };
}

function topTwo(d: WDeal): [HandValue, HandValue | undefined] {
  const sorted = d.result.hands.map((h) => h.hand).sort((a, b) => compareHands(b, a));
  return [sorted[0], sorted[1]];
}

type WPredicate = (d: WDeal) => boolean;
const closeHands: WPredicate = (d) => { const [a, b] = topTwo(d); return !!b && a.category === b.category; };
const kickerBattle: WPredicate = (d) => d.skills.includes("kicker-comparison") && !d.fullSplit;
const tricky: WPredicate = (d) => d.skills.some((s) => ["counterfeit", "full-house-comparison", "flush-comparison", "straight-comparison", "quads-kicker", "board-play-split", "two-pair-comparison"].includes(s));
const anyDeal: WPredicate = () => true;

const W_LEVELS: Record<Level, { players: number; splitChance: number; predicates: { item: WPredicate; weight: number }[] }> = {
  1: { players: 2, splitChance: 0.08, predicates: [{ item: anyDeal, weight: 1 }] },
  2: { players: 3, splitChance: 0.10, predicates: [{ item: closeHands, weight: 1 }, { item: anyDeal, weight: 1 }] },
  3: { players: 4, splitChance: 0.12, predicates: [{ item: closeHands, weight: 4 }, { item: anyDeal, weight: 1 }] },
  4: { players: 5, splitChance: 0.15, predicates: [{ item: kickerBattle, weight: 3 }, { item: closeHands, weight: 2 }] },
  5: { players: 6, splitChance: 0.18, predicates: [{ item: tricky, weight: 4 }, { item: kickerBattle, weight: 1 }] },
};

export function generateWinner(opts: GenerateOptions = {}): WinnerScenario {
  const seed = opts.seed ?? randomSeed();
  const level = levelOf(opts);
  const rng = createRng(seed);
  const cfg = W_LEVELS[level];
  const wantSplit = rng.chance(cfg.splitChance);
  const predicate = weightedPick(rng, cfg.predicates);
  const weak = weakFor("winner", seed, opts.weakSkills);
  const wantWeak = weak.length > 0;
  const buttonSeat = rng.between(1, cfg.players);

  let fallback: WDeal | null = null;
  let chosen: WDeal | null = null;
  const maxTries = wantSplit ? 6000 : 2000;
  for (let t = 0; t < maxTries; t++) {
    const d = dealWinner(rng, cfg.players);
    if (d.partialSplit) continue; // MVP: only complete splits are generated (engine still supports partial ones)
    if (fallback === null) fallback = d;
    if (wantSplit) { if (d.fullSplit) { chosen = d; break; } continue; }
    if (d.fullSplit) continue;
    if (wantWeak && t < 1500) {
      if (hasWeak(d.skills, weak)) { chosen = d; break; }
      continue;
    }
    if (predicate(d)) { chosen = d; break; }
  }
  const d = chosen ?? fallback;
  if (!d) throw new Error("generateWinner: could not produce a scenario");
  return {
    mode: "winner",
    seed,
    level,
    skills: d.skills,
    board: d.board,
    buttonSeat,
    players: d.players,
    answer: {
      winners: d.result.winners.slice().sort((a, b) => a - b),
      split: d.result.winners.length > 1,
      hands: d.result.hands.map((h) => ({ seat: h.id, hand: h.hand })),
    },
  };
}

// ---------------------------------------------------------------------------
// Betting simulation (POT / SIDE POT)

export interface BlindLevel { sb: number; bb: number }
export const BLIND_LEVELS: readonly BlindLevel[] = [
  { sb: 1, bb: 2 }, { sb: 1, bb: 3 }, { sb: 2, bb: 5 }, { sb: 5, bb: 10 }, { sb: 10, bb: 20 },
  { sb: 25, bb: 50 }, { sb: 50, bb: 100 }, { sb: 100, bb: 200 }, { sb: 200, bb: 400 }, { sb: 300, bb: 600 }, { sb: 500, bb: 1000 },
];

interface SimConfig {
  players: PlayerSetup[];
  buttonSeat: number;
  sb: number;
  bb: number;
  ante: number;
  /** Chip denomination used to round bet sizes. */
  unit: number;
  /** Last street to play (the hand may end earlier when everyone folds). */
  lastStreet: Street;
  style: "deep" | "shove";
  /** 0..1, how often players raise instead of calling. */
  aggression: number;
}

function roundTo(amount: number, unit: number): number {
  return Math.round(amount / unit) * unit;
}

function clampNice(amount: number, min: number, max: number, unit: number): number {
  let a = roundTo(amount, unit);
  if (a < min) a = min;
  if (a > max) a = max;
  return a;
}

function choosePreflopRaise(rng: Rng, state: HandState, la: { min: number; max: number }, unit: number): number {
  const bb = state.bigBlind;
  const raisesSoFar = state.log.filter((e) => e.street === "preflop" && (e.type === "raise" || e.type === "all_in")).length;
  const mult = raisesSoFar === 0 ? rng.pick([2, 2.2, 2.5, 3, 3, 3.5, 4]) : rng.pick([2.2, 2.5, 3, 3.5]);
  const target = raisesSoFar === 0 ? bb * mult : state.currentBet * mult;
  return clampNice(target, la.min, la.max, unit);
}

function choosePostflopSize(rng: Rng, pot: number, min: number, max: number, unit: number, currentBet: number): number {
  const frac = rng.pick([0.33, 0.5, 0.5, 0.66, 0.75, 1, 1.25]);
  const target = currentBet === 0 ? pot * frac : currentBet * rng.pick([2.2, 2.5, 3, 3.5]);
  return clampNice(target, min, max, unit);
}

function pickDeepAction(rng: Rng, state: HandState, cfg: SimConfig): Action {
  const la = legalActions(state);
  const seat = la.seat;
  const pot = state.players.reduce((s, p) => s + p.totalContribution, 0);
  const raisesThisStreet = state.log.filter((e) => e.street === state.street && (e.type === "raise" || e.type === "bet" || e.type === "all_in")).length;
  const ag = cfg.aggression;
  if (state.street === "preflop") {
    if (la.check) return la.raise && rng.chance(0.35 + ag * 0.3) ? { seat, type: "raise", amount: choosePreflopRaise(rng, state, la.raise, cfg.unit) } : { seat, type: "check" };
    const facingRaise = state.currentBet > state.bigBlind;
    const r = rng.next();
    if (la.raise && raisesThisStreet < 3 && r < (facingRaise ? 0.12 + ag * 0.15 : 0.35 + ag * 0.25)) {
      return { seat, type: "raise", amount: choosePreflopRaise(rng, state, la.raise, cfg.unit) };
    }
    if (r < (facingRaise ? 0.6 : 0.75)) return { seat, type: "call" };
    return { seat, type: "fold" };
  }
  if (la.check) {
    if (la.bet && rng.chance(0.35 + ag * 0.3)) {
      return { seat, type: "bet", amount: choosePostflopSize(rng, pot, la.bet.min, la.bet.max, cfg.unit, 0) };
    }
    return { seat, type: "check" };
  }
  const r = rng.next();
  if (la.raise && raisesThisStreet < 3 && r < 0.12 + ag * 0.2) {
    return { seat, type: "raise", amount: choosePostflopSize(rng, pot, la.raise.min, la.raise.max, cfg.unit, state.currentBet) };
  }
  if (r < 0.65) return { seat, type: "call" };
  return { seat, type: "fold" };
}

function pickShoveAction(rng: Rng, state: HandState, cfg: SimConfig): Action {
  const la = legalActions(state);
  const seat = la.seat;
  const p = state.players.find((x) => x.seat === seat)!;
  const pot = state.players.reduce((s, x) => s + x.totalContribution, 0);
  const r = rng.next();
  const canShove = la.allIn !== null;
  if (state.street === "preflop") {
    if (la.check) return { seat, type: r < 0.5 || !canShove ? "check" : "all_in" };
    if (canShove && r < 0.42) return { seat, type: "all_in" };
    if (la.raise && r < 0.55) return { seat, type: "raise", amount: choosePreflopRaise(rng, state, la.raise, cfg.unit) };
    if (r < 0.82) return { seat, type: "call" };
    return { seat, type: "fold" };
  }
  if (la.check) {
    if (canShove && r < 0.35) return { seat, type: "all_in" };
    if (la.bet && r < 0.6) return { seat, type: "bet", amount: choosePostflopSize(rng, pot, la.bet.min, Math.min(la.bet.max, p.stack), cfg.unit, 0) };
    return { seat, type: "check" };
  }
  if (canShove && r < 0.4) return { seat, type: "all_in" };
  if (r < 0.75) return { seat, type: "call" };
  return { seat, type: "fold" };
}

/** Simulate a hand with the betting engine, choosing only legal actions. */
export function simulateHand(rng: Rng, cfg: SimConfig): { history: HandHistory; state: HandState; streetsPlayed: Street[] } {
  const history: HandHistory = {
    players: cfg.players.map((p) => ({ ...p })),
    buttonSeat: cfg.buttonSeat,
    smallBlind: cfg.sb,
    bigBlind: cfg.bb,
    ante: cfg.ante,
    streets: [],
  };
  const state = startHand(history);
  const lastIdx = STREETS.indexOf(cfg.lastStreet);
  const streetsPlayed: Street[] = [];
  for (let i = 0; i <= lastIdx; i++) {
    const street = STREETS[i];
    if (i > 0) {
      if (state.handOver) break;
      startStreet(state, street);
    }
    const actions: Action[] = [];
    let guard = 0;
    while (!isRoundComplete(state)) {
      if (++guard > 300) throw new Error("simulateHand: betting did not terminate");
      const a = cfg.style === "deep" ? pickDeepAction(rng, state, cfg) : pickShoveAction(rng, state, cfg);
      applyAction(state, a);
      actions.push(a);
    }
    history.streets.push({ street, actions });
    streetsPlayed.push(street);
    if (state.handOver) break;
  }
  return { history, state, streetsPlayed };
}

function boardFor(rng: Rng, streets: readonly Street[]): Card[] {
  const deal = dealer(rng);
  const last = streets[streets.length - 1];
  const n = last === "preflop" ? 0 : last === "flop" ? 3 : last === "turn" ? 4 : 5;
  return deal(n);
}

function makePlayers(rng: Rng, count: number, stackFor: (i: number) => number): PlayerSetup[] {
  const players: PlayerSetup[] = [];
  for (let i = 0; i < count; i++) players.push({ seat: i + 1, name: playerName(i + 1), stack: stackFor(i) });
  return players;
}

// ---------------------------------------------------------------------------
// POT

const POT_LEVELS: Record<Level, { players: number[]; lastStreet: Street[]; aggression: number; minRaises: number }> = {
  1: { players: [2, 3, 3, 4], lastStreet: ["preflop"], aggression: 0.3, minRaises: 0 },
  2: { players: [3, 4, 4, 5], lastStreet: ["flop", "flop", "preflop"], aggression: 0.4, minRaises: 1 },
  3: { players: [3, 4, 5, 6], lastStreet: ["turn", "turn", "flop"], aggression: 0.5, minRaises: 1 },
  4: { players: [4, 5, 6, 7], lastStreet: ["river", "river", "turn"], aggression: 0.6, minRaises: 2 },
  5: { players: [6, 7, 8, 9], lastStreet: ["river"], aggression: 0.8, minRaises: 3 },
};

export function generatePot(opts: GenerateOptions = {}): PotScenario {
  const seed = opts.seed ?? randomSeed();
  const level = levelOf(opts);
  const rng = createRng(seed);
  const cfg = POT_LEVELS[level];
  const blind = rng.pick(BLIND_LEVELS);
  const unit = blind.sb;
  const playerCount = rng.pick(cfg.players);
  let fallback: PotScenario | null = null;
  for (let t = 0; t < 200; t++) {
    const players = makePlayers(rng, playerCount, () => roundTo(blind.bb * rng.between(80, 250), unit));
    const buttonSeat = rng.between(1, playerCount);
    const { history, state, streetsPlayed } = simulateHand(rng, {
      players, buttonSeat, sb: blind.sb, bb: blind.bb, ante: 0, unit, lastStreet: rng.pick(cfg.lastStreet), style: "deep", aggression: cfg.aggression,
    });
    // Deep-stack pot drills: no all-ins (that is what SIDE POT mode is for),
    // and something must have happened beyond the blinds.
    if (state.players.some((p) => p.allIn)) continue;
    const result = calculatePot(history);
    if (result.totalContributed <= blind.sb + blind.bb) continue;
    const board = boardFor(rng, streetsPlayed);
    const scenario: PotScenario = { mode: "pot", seed, level, skills: classifyPot(result), history, board, result, answer: { pot: result.pot } };
    if (fallback === null) fallback = scenario;
    const raises = state.log.filter((e) => e.type === "raise" || e.type === "bet").length;
    if (raises < cfg.minRaises) continue;
    // Level 1 is preflop only; higher levels should actually reach their target street.
    if (level >= 2 && streetsPlayed.length < 2) continue;
    return scenario;
  }
  if (fallback) return fallback;
  throw new Error("generatePot: could not produce a scenario");
}

// ---------------------------------------------------------------------------
// SIDE POT

const SP_LEVELS: Record<Level, { players: number[]; pots: [number, number]; preflopOnly: number; needFoldedOrUncalled: boolean; noFolds: boolean }> = {
  1: { players: [3], pots: [2, 2], preflopOnly: 1, needFoldedOrUncalled: false, noFolds: true },
  2: { players: [3, 4], pots: [2, 2], preflopOnly: 1, needFoldedOrUncalled: false, noFolds: false },
  3: { players: [4, 4, 5], pots: [3, 3], preflopOnly: 0.8, needFoldedOrUncalled: false, noFolds: false },
  4: { players: [4, 5, 5], pots: [2, 4], preflopOnly: 0.6, needFoldedOrUncalled: true, noFolds: false },
  5: { players: [5, 6, 6], pots: [3, 6], preflopOnly: 0.4, needFoldedOrUncalled: false, noFolds: false },
};

export function generateSidePot(opts: GenerateOptions = {}): SidePotScenario {
  const seed = opts.seed ?? randomSeed();
  const level = levelOf(opts);
  const rng = createRng(seed);
  const cfg = SP_LEVELS[level];
  const blind = rng.pick(BLIND_LEVELS);
  const unit = blind.sb;
  const playerCount = rng.pick(cfg.players);
  let fallback: SidePotScenario | null = null;
  const pickLast = (): Street => (rng.chance(cfg.preflopOnly) ? "preflop" : rng.pick(["flop", "turn", "river"] as Street[]));
  for (let t = 0; t < 1500; t++) {
    const players = makePlayers(rng, playerCount, () => roundTo(blind.bb * rng.between(3, 60), unit));
    const buttonSeat = rng.between(1, playerCount);
    const { history, state, streetsPlayed } = simulateHand(rng, {
      players, buttonSeat, sb: blind.sb, bb: blind.bb, ante: 0, unit, lastStreet: pickLast(), style: "shove", aggression: 0.7,
    });
    if (state.players.filter((p) => !p.folded).length < 2) continue; // no showdown, no side pot question
    const result = calculatePot(history);
    const pots = result.breakdown.pots.length;
    if (pots < 2) continue; // must have at least one side pot
    const board = boardFor(rng, streetsPlayed);
    const scenario: SidePotScenario = {
      mode: "side-pot", seed, level, skills: classifySidePot(result), history, board, result,
      answer: { pots: result.breakdown.pots, uncalled: result.breakdown.uncalled },
    };
    if (fallback === null) fallback = scenario;
    if (pots < cfg.pots[0] || pots > cfg.pots[1]) continue;
    if (cfg.noFolds && state.players.some((p) => p.folded)) continue;
    if (cfg.needFoldedOrUncalled && !(result.contributions.some((c) => c.folded && c.amount > 0) || result.breakdown.uncalled)) continue;
    return scenario;
  }
  if (fallback) return fallback;
  throw new Error("generateSidePot: could not produce a scenario");
}

// ---------------------------------------------------------------------------

export function generateScenario(mode: Mode, opts: GenerateOptions = {}): Scenario {
  switch (mode) {
    case "hand-reading": return generateHandReading(opts);
    case "winner": return generateWinner(opts);
    case "pot": return generatePot(opts);
    case "side-pot": return generateSidePot(opts);
  }
}

/**
 * QUICK TRAINING: pick a mode at random, weighted toward the modes the trainee
 * is weakest at (weights are supplied by the stats layer; equal when unknown).
 */
export function pickQuickMode(seed: number, modeWeights?: Partial<Record<Mode, number>>): Mode {
  const rng = createRng(seed ^ 0x9e3779b9);
  return weightedPick(rng, MODES.map((m) => ({ item: m, weight: Math.max(0.05, modeWeights?.[m] ?? 1) })));
}

export { HAND_CATEGORIES };
