/**
 * Random training scenarios. Nothing here knows the "answer" up front: every
 * scenario is generated by dealing cards / simulating legal betting with the
 * engine, and the answer is then DERIVED by the rules engine
 * (evaluateHand / determineWinners / calculatePot).
 */
import { Card } from "./cards";
import { createDeck } from "./deck";
import { createRng, randomSeed, Rng, shuffle } from "./shuffle";
import { evaluateHand, HandCategory, HandValue, HAND_CATEGORIES } from "./handEvaluator";
import { determineWinners } from "./handComparator";
import {
  Action, applyAction, HandHistory, HandState, isRoundComplete, legalActions, PlayerSetup, startHand, startStreet, Street, STREETS,
} from "./betting";
import { calculatePot, PotResult } from "./potCalculator";
import { Pot } from "./sidePotCalculator";

export type Mode = "hand-reading" | "winner" | "pot" | "side-pot";
export const MODES: readonly Mode[] = ["hand-reading", "winner", "pot", "side-pot"];

export interface SeatCards {
  seat: number;
  name: string;
  holeCards: Card[];
}

export interface HandReadingScenario {
  mode: "hand-reading";
  seed: number;
  holeCards: Card[];
  board: Card[];
  answer: { category: HandCategory; hand: HandValue };
}

export interface WinnerScenario {
  mode: "winner";
  seed: number;
  board: Card[];
  buttonSeat: number;
  players: SeatCards[];
  answer: {
    /** All winning seats. Length > 1 means a split pot. */
    winners: number[];
    split: boolean;
    hands: { seat: number; hand: HandValue }[];
  };
}

export interface PotScenario {
  mode: "pot";
  seed: number;
  history: HandHistory;
  /** Community cards dealt for the streets that were played (display only). */
  board: Card[];
  result: PotResult;
  answer: { pot: number };
}

export interface SidePotScenario {
  mode: "side-pot";
  seed: number;
  history: HandHistory;
  board: Card[];
  result: PotResult;
  answer: { pots: Pot[]; uncalled: { seat: number; amount: number } | null };
}

export type Scenario = HandReadingScenario | WinnerScenario | PotScenario | SidePotScenario;

// ---------------------------------------------------------------------------
// Card dealing helpers

function dealer(rng: Rng) {
  const deck = shuffle(createDeck(), rng);
  let i = 0;
  return (n: number): Card[] => {
    if (i + n > deck.length) throw new Error("deck exhausted");
    const out = deck.slice(i, i + n);
    i += n;
    return out;
  };
}

// ---------------------------------------------------------------------------
// HAND READING

const HAND_READING_WEIGHTS: Record<HandCategory, number> = {
  [HandCategory.HighCard]: 8,
  [HandCategory.OnePair]: 14,
  [HandCategory.TwoPair]: 16,
  [HandCategory.ThreeOfAKind]: 12,
  [HandCategory.Straight]: 14,
  [HandCategory.Flush]: 13,
  [HandCategory.FullHouse]: 12,
  [HandCategory.FourOfAKind]: 5,
  [HandCategory.StraightFlush]: 6,
};

function weightedPick<T extends string | number>(rng: Rng, weights: Record<T, number>): T {
  const entries = Object.entries(weights) as [string, number][];
  const total = entries.reduce((s, [, w]) => s + w, 0);
  let r = rng.next() * total;
  for (const [k, w] of entries) {
    r -= w;
    if (r < 0) return (typeof entries[0][0] === "string" && Number.isNaN(Number(k)) ? k : Number(k)) as T;
  }
  return Number(entries[entries.length - 1][0]) as T;
}

export function generateHandReading(seed: number = randomSeed()): HandReadingScenario {
  const rng = createRng(seed);
  const target = weightedPick(rng, HAND_READING_WEIGHTS) as HandCategory;
  // Rejection sampling keeps every deal an honest random 7 cards while making
  // rare categories show up often enough to train on.
  const maxTries = 30000;
  let last: { hole: Card[]; board: Card[]; hand: HandValue } | null = null;
  for (let t = 0; t < maxTries; t++) {
    const deal = dealer(rng);
    const hole = deal(2);
    const board = deal(5);
    const hand = evaluateHand([...hole, ...board]);
    last = { hole, board, hand };
    if (hand.category === target) break;
  }
  const { hole, board, hand } = last!;
  return { mode: "hand-reading", seed, holeCards: hole, board, answer: { category: hand.category, hand } };
}

// ---------------------------------------------------------------------------
// WINNER

function seatName(seat: number): string {
  return `Seat ${seat}`;
}

export function generateWinner(seed: number = randomSeed()): WinnerScenario {
  const rng = createRng(seed);
  const wantSplit = rng.chance(0.15);
  const wantClose = !wantSplit && rng.chance(0.5);
  const playerCount = wantSplit ? rng.pick([2, 2, 3]) : rng.pick([2, 2, 3, 3, 4]);
  const buttonSeat = rng.between(1, playerCount);

  let best: { board: Card[]; players: SeatCards[]; result: ReturnType<typeof determineWinners<number>> } | null = null;
  const maxTries = wantSplit ? 4000 : 60;
  for (let t = 0; t < maxTries; t++) {
    const deal = dealer(rng);
    const players: SeatCards[] = [];
    for (let s = 1; s <= playerCount; s++) players.push({ seat: s, name: seatName(s), holeCards: deal(2) });
    const board = deal(5);
    const result = determineWinners(players.map((p) => ({ id: p.seat, holeCards: p.holeCards })), board);
    const fullSplit = result.winners.length === players.length;
    const partialSplit = result.winners.length > 1 && !fullSplit;
    if (partialSplit) continue; // MVP: only complete splits are generated (engine still supports partial ones)
    if (best === null) best = { board, players, result };
    if (wantSplit && fullSplit) { best = { board, players, result }; break; }
    if (!wantSplit && !fullSplit) {
      best = { board, players, result };
      if (!wantClose) break;
      // "close" = top two hands share a category (kicker / tie-break practice)
      const sorted = result.hands.map((h) => h.hand).sort((a, b) => b.category - a.category);
      if (sorted.length >= 2 && sorted[0].category === sorted[1].category) break;
    }
  }
  if (best === null) throw new Error("generateWinner: could not produce a scenario");
  const { board, players, result } = best;
  return {
    mode: "winner",
    seed,
    board,
    buttonSeat,
    players,
    answer: {
      winners: result.winners.slice().sort((a, b) => a - b),
      split: result.winners.length > 1,
      hands: result.hands.map((h) => ({ seat: h.id, hand: h.hand })),
    },
  };
}

// ---------------------------------------------------------------------------
// Betting simulation (POT / SIDE POT)

export interface BlindLevel { sb: number; bb: number }
export const BLIND_LEVELS: readonly BlindLevel[] = [
  { sb: 1, bb: 2 }, { sb: 1, bb: 3 }, { sb: 2, bb: 5 }, { sb: 5, bb: 10 }, { sb: 10, bb: 20 },
  { sb: 25, bb: 50 }, { sb: 50, bb: 100 }, { sb: 100, bb: 200 }, { sb: 200, bb: 400 }, { sb: 300, bb: 600 },
];

interface SimConfig {
  players: PlayerSetup[];
  buttonSeat: number;
  sb: number;
  bb: number;
  /** Chip denomination used to round bet sizes. */
  unit: number;
  /** Last street to play (the hand may end earlier when everyone folds). */
  lastStreet: Street;
  style: "deep" | "shove";
}

function roundTo(amount: number, unit: number): number {
  return Math.round(amount / unit) * unit;
}

function clampNice(amount: number, min: number, max: number, unit: number): number {
  let a = roundTo(amount, unit);
  if (a < min) a = min;
  if (a > max) a = max;
  return a;
}

function choosePreflopRaise(rng: Rng, state: HandState, la: NonNullable<ReturnType<typeof legalActions>["raise"]>, unit: number): number {
  const bb = state.bigBlind;
  const raisesSoFar = state.log.filter((e) => e.street === "preflop" && (e.type === "raise" || e.type === "all_in")).length;
  const mult = raisesSoFar === 0 ? rng.pick([2, 2.2, 2.5, 3, 3, 3.5, 4]) : rng.pick([2.2, 2.5, 3, 3.5]);
  const target = raisesSoFar === 0 ? bb * mult : state.currentBet * mult;
  return clampNice(target, la.min, la.max, unit);
}

function choosePostflopSize(rng: Rng, pot: number, min: number, max: number, unit: number, currentBet: number): number {
  const frac = rng.pick([0.33, 0.5, 0.5, 0.66, 0.75, 1, 1.25]);
  const target = currentBet === 0 ? pot * frac : currentBet * rng.pick([2.2, 2.5, 3, 3.5]);
  return clampNice(target, min, max, unit);
}

function pickDeepAction(rng: Rng, state: HandState, unit: number): Action {
  const la = legalActions(state);
  const seat = la.seat;
  const pot = state.players.reduce((s, p) => s + p.totalContribution, 0);
  const raisesThisStreet = state.log.filter((e) => e.street === state.street && (e.type === "raise" || e.type === "bet" || e.type === "all_in")).length;
  if (state.street === "preflop") {
    if (la.check) return { seat, type: rng.chance(0.65) ? "check" : "raise", amount: la.raise ? choosePreflopRaise(rng, state, la.raise, unit) : undefined };
    const facingRaise = state.currentBet > state.bigBlind;
    const r = rng.next();
    if (la.raise && raisesThisStreet < 3 && r < (facingRaise ? 0.18 : 0.45)) {
      return { seat, type: "raise", amount: choosePreflopRaise(rng, state, la.raise, unit) };
    }
    if (r < (facingRaise ? 0.6 : 0.75)) return { seat, type: "call" };
    return { seat, type: "fold" };
  }
  // postflop
  if (la.check) {
    if (la.bet && rng.chance(0.45)) {
      return { seat, type: "bet", amount: choosePostflopSize(rng, pot, la.bet.min, la.bet.max, unit, 0) };
    }
    return { seat, type: "check" };
  }
  const r = rng.next();
  if (la.raise && raisesThisStreet < 3 && r < 0.2) {
    return { seat, type: "raise", amount: choosePostflopSize(rng, pot, la.raise.min, la.raise.max, unit, state.currentBet) };
  }
  if (r < 0.65) return { seat, type: "call" };
  return { seat, type: "fold" };
}

function pickShoveAction(rng: Rng, state: HandState, unit: number): Action {
  const la = legalActions(state);
  const seat = la.seat;
  const p = state.players.find((x) => x.seat === seat)!;
  const pot = state.players.reduce((s, x) => s + x.totalContribution, 0);
  const r = rng.next();
  const canShove = la.allIn !== null;
  if (state.street === "preflop") {
    if (la.check) return { seat, type: r < 0.5 || !canShove ? "check" : "all_in" };
    if (canShove && r < 0.42) return { seat, type: "all_in" };
    if (la.raise && r < 0.55) return { seat, type: "raise", amount: choosePreflopRaise(rng, state, la.raise, unit) };
    if (r < 0.82) return { seat, type: "call" };
    return { seat, type: "fold" };
  }
  if (la.check) {
    if (canShove && r < 0.35) return { seat, type: "all_in" };
    if (la.bet && r < 0.6) return { seat, type: "bet", amount: choosePostflopSize(rng, pot, la.bet.min, Math.min(la.bet.max, p.stack), unit, 0) };
    return { seat, type: "check" };
  }
  if (canShove && r < 0.4) return { seat, type: "all_in" };
  if (r < 0.75) return { seat, type: "call" };
  return { seat, type: "fold" };
}

/** Simulate a hand with the betting engine, choosing only legal actions. */
export function simulateHand(rng: Rng, cfg: SimConfig): { history: HandHistory; state: HandState; streetsPlayed: Street[] } {
  const history: HandHistory = {
    players: cfg.players.map((p) => ({ ...p })),
    buttonSeat: cfg.buttonSeat,
    smallBlind: cfg.sb,
    bigBlind: cfg.bb,
    streets: [],
  };
  const state = startHand(history);
  const lastIdx = STREETS.indexOf(cfg.lastStreet);
  const streetsPlayed: Street[] = [];
  for (let i = 0; i <= lastIdx; i++) {
    const street = STREETS[i];
    if (i > 0) {
      if (state.handOver) break;
      startStreet(state, street);
    }
    const actions: Action[] = [];
    let guard = 0;
    while (!isRoundComplete(state)) {
      if (++guard > 200) throw new Error("simulateHand: betting did not terminate");
      const a = cfg.style === "deep" ? pickDeepAction(rng, state, cfg.unit) : pickShoveAction(rng, state, cfg.unit);
      applyAction(state, a);
      actions.push(a);
    }
    history.streets.push({ street, actions });
    streetsPlayed.push(street);
    if (state.handOver) break;
  }
  return { history, state, streetsPlayed };
}

function boardFor(rng: Rng, streets: readonly Street[]): Card[] {
  const deal = dealer(rng);
  const last = streets[streets.length - 1];
  const n = last === "preflop" ? 0 : last === "flop" ? 3 : last === "turn" ? 4 : 5;
  return deal(n);
}

function pickLastStreet(rng: Rng): Street {
  const r = rng.next();
  if (r < 0.2) return "preflop";
  if (r < 0.55) return "flop";
  if (r < 0.8) return "turn";
  return "river";
}

function makePlayers(rng: Rng, count: number, stackFor: (i: number) => number): PlayerSetup[] {
  const players: PlayerSetup[] = [];
  for (let i = 0; i < count; i++) players.push({ seat: i + 1, name: seatName(i + 1), stack: stackFor(i) });
  return players;
}

// ---------------------------------------------------------------------------
// POT

export function generatePot(seed: number = randomSeed()): PotScenario {
  const rng = createRng(seed);
  const level = rng.pick(BLIND_LEVELS);
  const unit = level.sb;
  const playerCount = rng.pick([2, 3, 3, 4, 4, 5, 6]);
  for (let t = 0; t < 100; t++) {
    const players = makePlayers(rng, playerCount, () => roundTo(level.bb * rng.between(80, 250), unit));
    const buttonSeat = rng.between(1, playerCount);
    const { history, state, streetsPlayed } = simulateHand(rng, {
      players, buttonSeat, sb: level.sb, bb: level.bb, unit, lastStreet: pickLastStreet(rng), style: "deep",
    });
    // Deep-stack pot drills: no all-ins (that is what SIDE POT mode is for),
    // and something must have happened beyond the blinds.
    if (state.players.some((p) => p.allIn)) continue;
    const result = calculatePot(history);
    if (result.totalContributed <= level.sb + level.bb) continue;
    const board = boardFor(rng, streetsPlayed);
    return { mode: "pot", seed, history, board, result, answer: { pot: result.pot } };
  }
  throw new Error("generatePot: could not produce a scenario");
}

// ---------------------------------------------------------------------------
// SIDE POT

export function generateSidePot(seed: number = randomSeed()): SidePotScenario {
  const rng = createRng(seed);
  const level = rng.pick(BLIND_LEVELS);
  const unit = level.sb;
  const playerCount = rng.pick([3, 3, 4, 4, 4, 5]);
  for (let t = 0; t < 400; t++) {
    const players = makePlayers(rng, playerCount, () => roundTo(level.bb * rng.between(3, 60), unit));
    const buttonSeat = rng.between(1, playerCount);
    const { history, state, streetsPlayed } = simulateHand(rng, {
      players, buttonSeat, sb: level.sb, bb: level.bb, unit, lastStreet: rng.chance(0.7) ? "preflop" : pickLastStreet(rng), style: "shove",
    });
    if (state.players.filter((p) => !p.folded).length < 2) continue; // no showdown, no side pot question
    const result = calculatePot(history);
    if (result.breakdown.pots.length < 2) continue; // must have at least one side pot
    const board = boardFor(rng, streetsPlayed);
    return {
      mode: "side-pot", seed, history, board, result,
      answer: { pots: result.breakdown.pots, uncalled: result.breakdown.uncalled },
    };
  }
  throw new Error("generateSidePot: could not produce a scenario");
}

// ---------------------------------------------------------------------------

export function generateScenario(mode: Mode, seed: number = randomSeed()): Scenario {
  switch (mode) {
    case "hand-reading": return generateHandReading(seed);
    case "winner": return generateWinner(seed);
    case "pot": return generatePot(seed);
    case "side-pot": return generateSidePot(seed);
  }
}

export { HAND_CATEGORIES };
